### ISSUE TITLE
Tag as v1.0.0

### ISSUE THREAD

**Issue by fd** [dimchansky/utfbom#1]
This package seems pretty stable now. So maybe it should be tagged as `v1.0.0` to help `(v)go`.
Also adding a `go.mod` file (before tagging) is a good idea:

```
module github.com/dimchansky/utfbom
```

**Comment by dimchansky** [comment]
I've never done this before, but it's a good idea. :) Will try to do it this week.

**Comment by dimchansky** [comment]
Done: https://github.com/dimchansky/utfbom/releases/tag/v1.0.0
