### ISSUE TITLE
Copyright notice in the license text

### ISSUE THREAD

**Issue by kgrigorev** [dimchansky/utfbom#4]
Hi,
We would like to use this nice package in our project, but our legal department says we are not allowed to do it because license text is missing valid copyright (line 189). Could you maybe put something in there? Thank you in advance.

**Comment by dimchansky** [comment]
I've added copyright notice. You'll find changes in the latest release: https://github.com/dimchansky/utfbom/releases/tag/v1.1.1

**Comment by kgrigorev** [comment]
@dimchansky Thank you very much!
